//Project Euler Second Problem
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <stdio.h>
#define HACKERRANK 0

long long sumFibonaccisBelow(long long);
void hackerrank();

int main(){
	
	if(!HACKERRANK){

		long long solution=0, limit=4000000;
		solution = sumFibonaccisBelow(limit);
		printf("%lld\n",solution);

	}
	
	if(HACKERRANK) hackerrank();

	return 0;
}

long long sumFibonaccisBelow(long long limit){
	long long sum=0, number=1, previous=0, temp=0;
	while (number < limit){
		if(number%2 == 0) sum += number;
		temp = number;
		number += previous;
		previous = temp;
	}
	return sum;
}

void hackerrank(){
	int testCases=0;
	scanf("%d",&testCases);

	for( int test = 0 ; test < testCases ; test++){
		long long solution=0,limit=0;
		scanf("%lld",&limit);
		solution = sumFibonaccisBelow(limit);
		printf("%lld\n",solution);
	}
}
