//Project Euler Second Problem
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <stdio.h>
#define VALOR_MAXIMO 4000000

int sumarFibonaccisParesMenoresA(int limite);

int main(){
	printf("Total: %d\n",sumarFibonaccisParesMenoresA(VALOR_MAXIMO));
	return 0;
}

int sumarFibonaccisParesMenoresA(int limite){
	int suma=0;	
	for (int numero=1,anterior=0; numero<VALOR_MAXIMO; numero=generarFibonacci(numero,anterior))
	if(generarFibonacci(numero,anterior)%2==0)
		suma=suma+numero;
}

int generarFibonacci(int a,int b){
	int fibonacci=a+b;:	
	return a+b;

}
