//Highly Divisible triangular number 
/*

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
	1: 1
	3: 1,3
	6: 1,2,3,6
    10: 1,2,5,10
	15: 1,3,5,15
	21: 1,3,7,21
	28: 1,2,4,7,14,28
	
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?*/

#include <stdio.h>
#include <math.h>
#include <time.h>
#define NUM_OF_FACTORS 500

int computeDivisorsOfN(int);
int getTriangleNumberUpToN(int);
int isPossiblePrime(int);
int cropSqrt(int);

int highestDivisors=0;

int main (){
	int result;
	clock_t begin =clock();
	for(int n=6;highestDivisors<NUM_OF_FACTORS;n++)
		if((result=computeDivisorsOfN(getTriangleNumberUpToN(n)))>=NUM_OF_FACTORS)
			printf("Triangle number %d Factors:%d\n",getTriangleNumberUpToN(n),result);
	
	clock_t end = clock();
	double timespent = end-begin;
	printf("Time:%lfs\n",timespent/CLOCKS_PER_SEC); 
	return 0;
}

int computeDivisorsOfN(int n){
	int totalDivisors=1,upperBound=cropSqrt(n);
	for (int divisor=2;divisor<=upperBound;divisor++){
		if(n%divisor==0){
			totalDivisors++;
			if(divisor!=n/divisor)
				totalDivisors++;
		}
	}
	if (totalDivisors>highestDivisors){
		highestDivisors=totalDivisors;
		printf (" found %d divisors for %d\n",totalDivisors,n);
	}
	return totalDivisors;
}

int getTriangleNumberUpToN(int n){
	return (int)(n*((n+1)/2.0));
}

int cropSqrt(int n){
	double sqr=sqrt(n);
	return (int)sqr;
}

