//Distinct Powers, Project Euler Problem 29
/* 
Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

2^2=4, 2^3=8, 2^4=16, 2^5=32
3^2=9, 3^3=27, 3^4=81, 3^5=243
4^2=16, 4^3=64, 4^4=256, 4^5=1024
5^2=25, 5^3=125, 5^4=625, 5^5=3125

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100? */

#include <stdio.h>

#define MAX 100
#define VERBOSE 1

int calculateRepeatedTerms();
int exponentExisted(int,int,int);
int power(int,int);

int main (){

	int totalTerms=(MAX-1)*(MAX-1);
	int totalRepeats=0;

	totalRepeats=calculateRepeatedTerms();
	printf("[Total terms]-[Repeated terms] %d-%d=%d\n",totalTerms,totalRepeats,totalTerms-totalRepeats);

	return 0;
}

int calculateRepeatedTerms(){
	int baseToRefactor, resultingExp;
	int repeats=0;
	
	for (int base=2; base*base<=MAX ; base++){
		if (base==4) base++;
		if (base==8) base++;
		if (base==9) base++;
		
		for (int exponent=2; exponent<=6 ; exponent++){
			baseToRefactor=power(base,exponent);

			if (baseToRefactor > MAX)break;
			
			for (int term=2; term <= MAX ; term++){
				resultingExp= exponent * term;
					if(exponentExisted(base,exponent,resultingExp))
						repeats++;
			}
		}
	}
	return repeats;
}


int exponentExisted(int base, int exponent,int resultingExp){
	int previousLimit=(exponent-1)*MAX;
	int previousExponent=exponent-1;

	while(previousExponent>0){
		if ( (resultingExp<=previousLimit) && (resultingExp%previousExponent==0) ){
			return 1;
		}
		previousLimit-=MAX;
		previousExponent--;
	}
	return 0;
}

int power(int base, int exponent){
	int result=1;
	while (exponent){
		result*=base;
		exponent--;
	}
	return result;
}

