//Pentagon numbers, Euler Project Problem 43
/*Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?*/

#include <stdio.h>
#include <math.h>
#define print(ref) printf(#ref"=%d\n",ref);
#define printl(ref) printf(#ref"=%ld\n",ref);
#define NUM_OF_PENTAGONS 2201

void fillWithPentagons(long*);
long solution(long*);
int isPentagonal(long);

int main(){
	long pentagons[NUM_OF_PENTAGONS]={0};

	fillWithPentagons(pentagons);

	printl(solution(pentagons))

	return 0;
}

void fillWithPentagons(long*array){
	for (int i=1; i < NUM_OF_PENTAGONS ; i++){
		array[i] = (int)(i * ( (3 * i - 1) / 2.0));
	}
}

long solution(long*pentagons){
	for (int k=1; k<NUM_OF_PENTAGONS ; k++){
		for (int j=k-1; j>0 ; j--){
			if (isPentagonal(pentagons[j]+pentagons[k]) && 
				isPentagonal(pentagons[k]-pentagons[j])){
				return pentagons[k]-pentagons[j];
			}
		}
	}
	return 0;
}

int isPentagonal(long number){
	double x = ( sqrt(24 * number + 1) + 1 ) /6.0;
	return x == (int)x;
}
