//Triangular, Pentagonal, Hexagonal, Euler Project Problem 45
/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	T_n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	P_n=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	H_n=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal. */

#include <stdio.h>
#include <math.h>
#define printl(ref) printf(#ref"=%ld\n",ref);

long hexagonal(int);
int isPentagonal(long);

int main(){
	int found=0, n=144;

	while (!found){
		if(isPentagonal(hexagonal(n))){
			printl(hexagonal(n));
			found++;
		}
		n++;
	}

	return 0;
}

long hexagonal(int n){
	return n * ( 2 * n - 1 );
}

int isPentagonal(long number){
	double x = ( sqrt(24 * number + 1) + 1 ) /6.0;
	return x == (int)x;
}
